https://github.com/ImageMagick/ImageMagick/issues/3152

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -818,9 +818,10 @@ LCMS_DELEGATE_FALSE
 LCMS_DELEGATE_TRUE
 LCMS2_LIBS
 LCMS2_CFLAGS
-JXL_LIBS
 JXL_DELEGATE_FALSE
 JXL_DELEGATE_TRUE
+JXL_LIBS
+JXL_CFLAGS
 JPEG_LIBS
 JPEG_DELEGATE_FALSE
 JPEG_DELEGATE_TRUE
@@ -1281,6 +1282,8 @@ GVC_CFLAGS
 GVC_LIBS
 HEIF_CFLAGS
 HEIF_LIBS
+JXL_CFLAGS
+JXL_LIBS
 LCMS2_CFLAGS
 LCMS2_LIBS
 LIBOPENJP2_CFLAGS
@@ -2041,7 +2044,7 @@ Optional Packages:
   --without-heic          disable HEIC support
   --without-jbig          disable JBIG support
   --without-jpeg          disable JPEG support
-  --without-jxl           disable JPEG-XL support
+  --with-jxl              enable JPEG-XL support
   --without-lcms          disable lcms (v1.1X) support
   --without-openjp2       disable OpenJP2 support
   --without-lqr           disable Liquid Rescale support
@@ -2114,6 +2117,8 @@ Some influential environment variables:
   GVC_LIBS    linker flags for GVC, overriding pkg-config
   HEIF_CFLAGS C compiler flags for HEIF, overriding pkg-config
   HEIF_LIBS   linker flags for HEIF, overriding pkg-config
+  JXL_CFLAGS  C compiler flags for JXL, overriding pkg-config
+  JXL_LIBS    linker flags for JXL, overriding pkg-config
   LCMS2_CFLAGS
               C compiler flags for LCMS2, overriding pkg-config
   LCMS2_LIBS  linker flags for LCMS2, overriding pkg-config
@@ -4555,7 +4560,7 @@ MAGICK_PATCHLEVEL_VERSION=59
 
 MAGICK_VERSION=7.0.10-59
 
-MAGICK_GIT_REVISION=18327:f7e785915:20210122
+MAGICK_GIT_REVISION=18337:af14c333a:20210123
 
 
 # Substitute library versioning
@@ -4585,7 +4590,7 @@ PACKAGE_LIB_VERSION=0x70A
 
 PACKAGE_LIB_VERSION_NUMBER=7,0,10,59
 
-PACKAGE_RELEASE_DATE=2021-01-22
+PACKAGE_RELEASE_DATE=2021-01-23
 
 
 # Ensure that make can run correctly
@@ -30576,150 +30581,96 @@ fi
 if test "$with_jxl" != 'yes'; then
     DISTCHECK_CONFIG_FLAGS="${DISTCHECK_CONFIG_FLAGS} --with-jxl=$with_jxl "
 fi
-if test "$enable_static" = 'yes'; then
-    if test "$with_utilities" = 'yes'; then
-        with_jxl='no'
-    fi
-fi
 
-# Check for the JPEG-XL library.
 have_jxl='no'
-JXL_LIBS=''
-if test "$with_jxl" != 'no'; then
+JXL_CFLAGS=""
+JXL_LIBS=""
+JXL_PKG=""
+if test "x$with_jxl" = "xyes"; then
   { $as_echo "$as_me:${as_lineno-$LINENO}: result: -------------------------------------------------------------" >&5
 $as_echo "-------------------------------------------------------------" >&6; }
-  { $as_echo "$as_me:${as_lineno-$LINENO}: checking for jpeg-xl" >&5
-$as_echo_n "checking for jpeg-xl... " >&6; }
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for libjxl >= 0.2.0" >&5
+$as_echo_n "checking for libjxl >= 0.2.0... " >&6; }
+
+if test -n "$JXL_CFLAGS"; then
+    pkg_cv_JXL_CFLAGS="$JXL_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libjxl >= 0.2.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libjxl >= 0.2.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_JXL_CFLAGS=`$PKG_CONFIG --cflags "libjxl >= 0.2.0" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$JXL_LIBS"; then
+    pkg_cv_JXL_LIBS="$JXL_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libjxl >= 0.2.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libjxl >= 0.2.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_JXL_LIBS=`$PKG_CONFIG --libs "libjxl >= 0.2.0" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        JXL_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "libjxl >= 0.2.0" 2>&1`
+        else
+	        JXL_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "libjxl >= 0.2.0" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$JXL_PKG_ERRORS" >&5
+
+	have_jxl=no
+elif test $pkg_failed = untried; then
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	have_jxl=no
+else
+	JXL_CFLAGS=$pkg_cv_JXL_CFLAGS
+	JXL_LIBS=$pkg_cv_JXL_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	have_jxl=yes
+fi
   { $as_echo "$as_me:${as_lineno-$LINENO}: result: " >&5
 $as_echo "" >&6; }
-  failed=0
-  passed=0
-  ac_fn_c_check_header_mongrel "$LINENO" "jxl/decode.h" "ac_cv_header_jxl_decode_h" "$ac_includes_default"
-if test "x$ac_cv_header_jxl_decode_h" = xyes; then :
-  passed=`expr $passed + 1`
-else
-  failed=`expr $failed + 1`
 fi
 
-
-  ac_fn_c_check_header_mongrel "$LINENO" "jxl/encode.h" "ac_cv_header_jxl_encode_h" "$ac_includes_default"
-if test "x$ac_cv_header_jxl_encode_h" = xyes; then :
-  passed=`expr $passed + 1`
-else
-  failed=`expr $failed + 1`
-fi
-
-
-  # This check should be changed once we have a .pc file for the JPEG-XL library.
-  if test "$enable_static" != 'yes'; then
-    { $as_echo "$as_me:${as_lineno-$LINENO}: checking for JxlDecoderCreate in -ljxl" >&5
-$as_echo_n "checking for JxlDecoderCreate in -ljxl... " >&6; }
-if ${ac_cv_lib_jxl_JxlDecoderCreate+:} false; then :
-  $as_echo_n "(cached) " >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-ljxl  $LIBS"
-cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char JxlDecoderCreate ();
-int
-main ()
-{
-return JxlDecoderCreate ();
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_c_try_link "$LINENO"; then :
-  ac_cv_lib_jxl_JxlDecoderCreate=yes
-else
-  ac_cv_lib_jxl_JxlDecoderCreate=no
-fi
-rm -f core conftest.err conftest.$ac_objext \
-    conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_jxl_JxlDecoderCreate" >&5
-$as_echo "$ac_cv_lib_jxl_JxlDecoderCreate" >&6; }
-if test "x$ac_cv_lib_jxl_JxlDecoderCreate" = xyes; then :
-  passed=`expr $passed + 1`
-else
-  failed=`expr $failed + 1`
-fi
-
-    { $as_echo "$as_me:${as_lineno-$LINENO}: checking for JxlEncoderCreate in -ljxl" >&5
-$as_echo_n "checking for JxlEncoderCreate in -ljxl... " >&6; }
-if ${ac_cv_lib_jxl_JxlEncoderCreate+:} false; then :
-  $as_echo_n "(cached) " >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-ljxl  $LIBS"
-cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char JxlEncoderCreate ();
-int
-main ()
-{
-return JxlEncoderCreate ();
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_c_try_link "$LINENO"; then :
-  ac_cv_lib_jxl_JxlEncoderCreate=yes
-else
-  ac_cv_lib_jxl_JxlEncoderCreate=no
-fi
-rm -f core conftest.err conftest.$ac_objext \
-    conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_jxl_JxlEncoderCreate" >&5
-$as_echo "$ac_cv_lib_jxl_JxlEncoderCreate" >&6; }
-if test "x$ac_cv_lib_jxl_JxlEncoderCreate" = xyes; then :
-  passed=`expr $passed + 1`
-else
-  failed=`expr $failed + 1`
-fi
-
-  fi
-
-  { $as_echo "$as_me:${as_lineno-$LINENO}: checking if jpeg-xl package is complete" >&5
-$as_echo_n "checking if jpeg-xl package is complete... " >&6; }
-  if test $passed -gt 0; then
-      if test $failed -gt 0; then
-          { $as_echo "$as_me:${as_lineno-$LINENO}: result: no -- some components failed test" >&5
-$as_echo "no -- some components failed test" >&6; }
-          have_jxl='no (failed tests)'
-      else
-          JXL_LIBS='-ljxl'
-          LIBS="$JXL_LIBS $LIBS"
+if test "$have_jxl" = 'yes'; then
 
 $as_echo "#define JXL_DELEGATE 1" >>confdefs.h
 
-          { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
-$as_echo "yes" >&6; }
-          have_jxl='yes'
-      fi
-  else
-      { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
-$as_echo "no" >&6; }
-  fi
+  CFLAGS="$JXL_CFLAGS $CFLAGS"
 fi
+
  if  test "$have_jxl" = 'yes'; then
   JXL_DELEGATE_TRUE=
   JXL_DELEGATE_FALSE='#'
@@ -30727,6 +30678,7 @@ else
   JXL_DELEGATE_TRUE='#'
   JXL_DELEGATE_FALSE=
 fi
+
 
 
 
